on:
  push:
    branches: main
    workflow_dispatch:

jobs:
  write-story:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            github::bvreede/madlibs

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Make story
        run: Rscript -e 'source("grocery_story.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add story.md
          git commit -m 'update the story'
          git push origin
