on:
  pull_request:
    branches:
      - main

jobs:
  write-story:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            github::bvreede/madlibs

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Make story
        run: Rscript -e 'source("stories.R")'
